example/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', include(wagtail_urls)),
]

wagtailcolourpicker/urls.py
from django.urls import path

from wagtailcolourpicker.views import chooser


app_name = 'wagtailcolourpicker'

urlpatterns = [
    path('chooser/', chooser, name='chooser'),
]

example/models.py
from wagtail.admin.edit_handlers import StreamFieldPanel
from wagtail.core.blocks import RichTextBlock
from wagtail.core.fields import StreamField
from wagtail.core.models import Page


class BasicPage(Page):

    body = StreamField([
        ('rich_text', RichTextBlock())
    ])

    # show in menu ticked by default
    show_in_menus_default = True

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]

wagtailcolourpicker/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from wagtailcolourpicker.utils.colour import get_colour_choices


class ColourRadioSelect(forms.widgets.RadioSelect):
    option_template_name = 'colourpicker/forms/widgets/colour_option.html'


class ColourForm(forms.Form):
    colour = forms.ChoiceField(
        label=_("Colours"),
        choices=get_colour_choices(),
        widget=ColourRadioSelect,
        required=False
    )

wagtailcolourpicker/views.py
from wagtail.admin.modal_workflow import render_modal_workflow

from wagtailcolourpicker.forms import ColourForm
from wagtailcolourpicker.utils.colour import get_feature_name_list, get_feature_name_upper


def chooser(request):
    if request.method == 'POST':
        form = ColourForm(request.POST)

        if form.is_valid():

            feature_name = ''
            if form.cleaned_data.get('colour'):
                feature_name = get_feature_name_upper(form.cleaned_data.get('colour'))

            all_features = get_feature_name_list()

            return render_modal_workflow(
                request, None, None, None,
                json_data={
                    'step': 'colour_chosen',
                    'toggled_feature': feature_name,
                    'all_features': all_features
                }
            )
    else:
        form = ColourForm()

    return render_modal_workflow(
        request, 'colourpicker/chooser/chooser.html', None,
        {'form': form},
        json_data={'step': 'chooser'}
    )

example/templates/example/basic_page.html
{% load i18n static wagtailcore_tags wagtailuserbar %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% firstof page.seo_title page.title %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
</head>
<body>
    <header>
        <div class="container">
            <h1>Wagtail ColourPicker</h1>
        </div>
    </header>
    <div class="container">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% for block in page.body %}
            {% include_block block %}
        {% endfor %}
    </div>
    {% wagtailuserbar %}
</body>
</html>

wagtailcolourpicker/templates/colourpicker/chooser/chooser.html
{% load wagtailimages_tags %}
{% load i18n %}
{% trans "Choose colour" as title_str %}
{% trans "Submit an empty form to remove the selected text colour" as subtitle_str %}
{% include "wagtailadmin/shared/header.html" with title=title_str subtitle=subtitle_str merged=1 %}

<div class="tab-content">
    <section id="form" class="active nice-padding">
        <form class="colour-form" action="{% url 'wagtailcolourpicker:chooser' %}" method="POST" novalidate>
            {% csrf_token %}
            <ul class="fields">
                {% for field in form %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
                {% endfor %}
                <li>
                    <button type="submit" class="button  button-longrunning"><span class="icon icon-spinner"></span><em>{% trans 'Select' %}</em></button>
                </li>
            </ul>
        </form>
    </section>
</div>

wagtailcolourpicker/templates/colourpicker/forms/widgets/colour_option.html
{% include "django/forms/widgets/input.html" %}
<label style="background: {{ widget.label }}" {% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %}></label>
<div style="text-align: center;"><small>{{ widget.label }}</small></div>